name: Ingest Google Places Data

on:
  workflow_dispatch:     # allows manual trigger
  schedule:
    - cron: "0 8 * * 0"  # runs every Sunday at 8 AM UTC

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python ingest_google.py
