name: Ingest Google Places Data and Save Images

on:
  workflow_dispatch:        # allows manual trigger
  schedule:
    - cron: "0 8 * * 0"     # runs every Sunday at 8 AM UTC

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary

      # Step 4: Run ingestion script
      - name: Run ingestion script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Starting ingestion..."
          python ingest_google.py
          echo "✅ Ingestion complete."
      
      - name: Debug check for images
        run: |
          echo "Checking image directory..."
          ls -R public || echo "❌ No public folder found"
          ls -R public/images || echo "❌ No images folder found"


      # Step 5: Commit and push any new or updated images
      - name: Commit and push downloaded images
        run: |
          echo "Committing new images..."
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git pull --rebase
          git add public/images || true
          git diff --cached --quiet || git commit -m "Add/Update Google Places images from ingestion"
          git push origin main || echo "No new images to push."
